# Generated by Django 4.2 on 2024-08-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('domicilio', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Importador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('domicilio', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_uni_venta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('fecha_cump', models.DateField()),
                ('nro_permiso', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
