# Generated by Django 4.2 on 2024-08-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercaderia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mercaderia',
            name='tipo_uni_venta',
        ),
        migrations.AddField(
            model_name='mercaderia',
            name='nomb_mer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercaderia',
            name='unidad_venta',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
