# Generated by Django 4.2 on 2024-08-31 19:29

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_mercaderia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportador',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, validators=[App.models.validate_cuit]),
        ),
    ]
