# Generated by Django 4.2 on 2024-08-31 19:40

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_exportador_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportador',
            name='cuit',
            field=models.IntegerField(max_length=11, unique=True, validators=[App.models.validate_cuit]),
        ),
    ]
