# Generated by Django 4.2 on 2024-08-31 20:03

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_exportador_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportador',
            name='cuit',
            field=models.IntegerField(unique=True, validators=[App.models.validate_cuit]),
        ),
        migrations.AlterField(
            model_name='importador',
            name='cuit',
            field=models.IntegerField(unique=True),
        ),
    ]
