# Generated by Django 4.2 on 2024-09-02 03:48

import App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_exportador_cuit_alter_importador_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportador',
            name='cuit',
            field=models.CharField(max_length=13, unique=True, validators=[App.validators.validate_cuit]),
        ),
        migrations.AlterField(
            model_name='importador',
            name='cuit',
            field=models.CharField(max_length=13, unique=True, validators=[App.validators.validate_cuit]),
        ),
    ]
